language: php
install:
  - pear install --alldeps package.xml
  - composer dumpautoload -o
php:
  - 5.4
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
before_script:
  - composer require phpunit/phpunit:"^4.8|^5.7"
script: ./vendor/bin/phpunit tests/
